id = "pylyzer"
name = "Pylyzer"
description = "pylyzer support."
version = "0.1.0"
schema_version = 1
authors = ["Sean Robinson <irobbierobinson@gmail.com>"]
repository = "https://github.com/robbierobs/pylyzer-zed"

[language_servers.pylyzer]
name = "Pylyzer"
languages = ["Python"]
